import:
  - ../common

normalization: softmax
num_classes: 2
data_len: 500
pretrained: false
batch_size: 16

###################
# Training Config
###################
num_workers: 8
epochs: 300
lr: 1.0e-4
weight_decay: 0.0
decay_rate: 0.1
smoothing: 0.0

###################
# Model Config
###################
tfg_kws:
  drop_rate: 0
  # drop_path: null
  drop_path_rate: 0.1

network_size: s

contrast_loss_weight: 0.0
smoothing_value: 0.0
gradient_accumulation_steps: 1
max_grad_norm: 1.0
lr_warmup_epochs: 5
# cosine
# linear
decay_type: cosine
patch_size: 16

warming_up_epoch: 80
