import:
  - ../common

normalization: softmax
num_classes: 2
data_len: 300
###################
# Training Config
###################
num_workers: 8
batch_size: 16
epochs: 200
lr: 3.0e-2
weight_decay: 0.0

###################
# Model Config
###################
# ViT-B_16
# ViT-B_32
# ViT-L_16
# ViT-L_32
# ViT-H_14
model_type: ViT-B_16
split: overlap
slide_step: 12
smoothing_value: 0.0
loss_scale: 0
gradient_accumulation_steps: 1
max_grad_norm: 1.0
warmup_steps: 500
# cosine
# linear
decay_type: cosine
num_steps: 10000
zero_head: true
