import:
  - ../common

num_classes: 2

###################
# Training Config
###################
num_workers: 4
batch_size: 16
epochs: 200
lr: 1.0e-3

###################
# Model Config
###################
pretrained: false
normalization: softmax
image_size: 448
net: inception_mixed_6e
num_attentions: 32
beta: 5.0e-2
